language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-20.0.0
    - android-19
before_install:
    - ./setup_env.sh ant
script:
  - ./gradlew clean build
  - ant clean
  - ant debug

