language: android
android:
  components:
    - build-tools-22.0.1
    # old build tools due to core lib
    - build-tools-20.0.0
    - android-22
    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
before_install:
  - rm pom.xml
script:
  - ./setup_env.sh gradle
  - ./gradlew clean
  - ./gradlew assembleDebug
  
